### ISSUE TITLE
Over-specified version constraints on dependencies

### ISSUE THREAD

**Issue by peti** [mgajda/json-autotype#15]
Hi,

this tool constrains the version of its dependencies to very old versions: http://packdeps.haskellers.com/feed?needle=json-autotype, and this seems to be needlessly. When I build the package with the latest version of all those dependencies, then the build and the test suite succeed just fine. Could you maybe edit those version constraints on Hackage to relax them a bit?

Best regards,
Peter

**Comment by mgajda** [comment]
Definitely! Please send me a message if you want to take ownership of this problem, and get added to Hackage maintainers of JSON-Autotype!

**Comment by peti** [comment]
Hi Michał,

> Please send me a message if you want to take ownership of this
> problem, and get added to Hackage maintainers of JSON-Autotype!

sure, I'd be happy to do that. My user name on Hackage is PeterSimons:

  https://hackage.haskell.org/user/PeterSimons

Best regards,
Peter

**Comment by mgajda** [comment]
I updated dependences for 1.0.17, and added you as a maintainer.

**Comment by peti** [comment]
Very cool, thank you!
