### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by peti** [mgajda/json-autotype#16]
We have accumulated a couple of changes in git and need to update the release on Hackage anyway to add support for GHC 8.4.1. How do you feel about releasing the current `master` as a new version?

EDIT: https://travis-ci.org/mgajda/json-autotype/builds/351679718 has succeeded meanwhile.

**Comment by mgajda** [comment]
Agreed.

**Comment by mgajda** [comment]
Done :-).
Please let me know if any desirable features still remain.
