### ISSUE TITLE
Test Suite Failing on GHC 8.4.1 with nightly-2018-03-25 snapshot 

### ISSUE THREAD

**Issue by jkachmar** [mgajda/json-autotype#17]
I'm seeing the following failure when I attempt to build `json-autotype-1.1.0` against the Stackage nightly-2018-03-25 snapshot:
```
test/TestExamples.hs:41:18: error:
    Variable not in scope: runghc :: [[Char]] -> IO ExitCode
   |
41 |     genResult <- runghc ["GenerateJSONParser.hs", filename, "--outputFilename", outputFilename]
   |                  ^^^^^^

test/TestExamples.hs:44:21: error:
    Variable not in scope: runghc :: [FilePath] -> IO ExitCode
   |
44 |     parserResult <- runghc [outputFilename, filename]
   |  
```
I'm disabling the test suite for `json-autotype` for the time being to get it into nightly-2018-03-26, but I'll re-enable it once the above is fixed/if you'd prefer that the package version be pinned to 1.0.18 until this is resolved

**Comment by mgajda** [comment]
This is fixed with the new release:
https://travis-ci.org/mgajda/json-autotype

Thanks for reporting!
