### ISSUE TITLE
[documentation] Explain methodology

### ISSUE THREAD

**Issue by ocramz** [mgajda/json-autotype#18]
> I should probably write a short paper to explain the methodology.

Or even just a paragraph in the README.

Pretty please? : )

**Comment by mgajda** [comment]
There is a whole talk about JSON-Autotype on Engineers.SG:
https://engineers.sg/video/json-autotype-1-0-haskell-sg--429

I will mention it in README.
Please let me know if you are satisfied.

Or let me know which journal accepts it as a paper.
