### ISSUE TITLE
Raise lens upper bound to use current 4.9

### ISSUE THREAD

**Issue by FranklinChen** [mgajda/json-autotype#4]
Use `lens` 4.9 https://github.com/ekmett/lens/commit/2c32b945417be57813578124387136a41377d08a in order to not break other libraries that have upgraded to `primitive` 0.6 https://github.com/haskell/primitive/commit/c46bb077c2042e2765510c87539569d4f6b0bcc0

**Comment by mgajda** [comment]
This version was not released on Hackage yet.

**Comment by FranklinChen** [comment]
Oops, I should have said that, to avoid confusion.

**Comment by mgajda** [comment]
Version constraint has been relaxed in the current release candidate (0.4).
